<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Pocketing 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130128

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Pocketing</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href='http://fonts.googleapis.com/css?family=Archivo+Narrow:400,700|Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <link href="<?php echo $this->basePath() ?>/AntonTonev/css/default.css" rel="stylesheet" type="text/css" media="all" />
<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<img src="<?php echo $this->basePath() ?>/AntonTonev/images/main-bg.jpg" width="1500" height="1000" alt="" id="full-screen-background-image" />
<div id="wrapper">
  <div id="header-wrapper">
    <div id="header" class="container">
      <div id="logo">
        <h1><a href="#">Pocketing</a></h1>
      </div>
      <div id="menu">
        <ul>
          <li class="active"><a href="#" accesskey="1" title="">Homepage</a></li>
          <li><a href="#" accesskey="2" title="">Our Events</a></li>
          <li><a href="#" accesskey="3" title="">Gallery</a></li>
          <li><a href="#" accesskey="4" title="">About Us</a></li>
          <li><a href="#" accesskey="5" title="">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div id="page" class="container">
    <div id="content">
      <div id="box1">
        
       <?php echo $this->content; ?>
        
      </div>
      <div>
        <ul class="style1">
          <li class="first">
            <h3><em><img src="<?php echo $this->basePath() ?>/AntonTonev/images/img02.jpg" alt="" width="130" height="130" class="alignleft border" /></em>Lorem ipsum dolor interdum</h3>
            <p>Ut vel nisl tristique justo ornare iaculis. Suspendisse suscipit, orci ac interdum viverra, nulla orci facilisis mi, a ultrices mi lectus vitae felis. Morbi suscipit adipiscing orci et blandit. Morbi a nulla ut tellus blandit placerat a quis eros.</p>
            <p><a href="#" class="button-style">Read More</a></p>
          </li>
          <li>
            <h3><em><img src="<?php echo $this->basePath() ?>/AntonTonev/images/img03.jpg" alt="" width="130" height="130" class="alignleft border" /></em>Magna phasellus etiam ultrices</h3>
            <p>Ut vel nisl tristique justo ornare iaculis. Suspendisse suscipit, orci ac interdum viverra, nulla orci facilisis mi, a ultrices mi lectus vitae felis. Morbi suscipit adipiscing orci et blandit. Morbi a nulla ut tellus blandit placerat a quis eros.</p>
            <p><a href="#" class="button-style">Read More</a></p>
          </li>
        </ul>
      </div>
    </div>
    <div id="sidebar">
      <h2>Fusce ultrices</h2>
      <ul class="style3">
        <li class="first">
          <p class="date">01-14-2013</p>
          <p><a href="#">Vestibulum laoreet lorem sed amet condimentum eget ultrices et mago porttitor nequese blandit.</a></p>
        </li>
        <li>
          <p class="date">01-13-2013</p>
          <p><a href="#">Vestibulum laoreet lorem sed amet condimentum eget ultrices et mago porttitor nequese blandit.</a></p>
        </li>
        <li>
          <p class="date">01-07-2013</p>
          <p><a href="#">Vestibulum laoreet lorem sed amet condimentum eget ultrices et mago porttitor nequese blandit.</a></p>
        </li>
      </ul>
    </div>
  </div>
  <div id="footer">
    <p>Copyright (c) 2013 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org">FCT</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
  </div>
</div>
</body>
</html>
