<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Flowering   
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20120506

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Flowering by FCT</title>
<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <link href="<?php echo $this->basePath(); ?>/IvelinaVelcheva/css/style.css" rel="stylesheet" type="text/css" media="screen" />
  
</head>
<body>
<div id="wrapper">
  <div id="header-wrapper">
    <div id="header">
      <div id="logo">
        <h1><a href="#">Flowering</a></h1>
        <p>template design by <a href="http://www.freecsstemplates.org/">FCT</a></p>
      </div>
    </div>
  </div>
  <!-- end #header -->
  <div id="menu">
    <ul>
      <li class="current_page_item"><a href="#">Homepage</a></li>
      <li><a href="#">Blog</a></li>
      <li><a href="#">Photos</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Links</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
  <!-- end #menu -->
  <div id="page">
    <div id="page-bgtop">
      <div id="page-bgbtm">
        <div id="content">
          <div class="post">
            <h2 class="title"><a href="#">Welcome to my page </a></h2>
            <p class="meta">Posted by <a href="#">Someone</a> on March 13, 2013
              &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
            <div class="entry">
              <p><img src="<?php echo $this->basePath(); ?>/IvelinaVelcheva/images/pics01.jpg" width="200" height="200" alt="" class="alignleft border" /></p>
              <?php echo $this->content; ?> 
            </div>
          </div>
          <div class="post">
            <h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
            <p class="meta">Posted by <a href="#">Someone</a> on May 01, 2012
              &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
            <div class="entry">
              <p><img src="<?php echo $this->basePath(); ?>/IvelinaVelcheva/images/pics02.jpg" width="200" height="200" alt="" class="alignleft border" />Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, consectetuer nisl felis ac diam. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. Mauris vitae nisl nec metus placerat consectetuer. </p>
            </div>
          </div>
          <div class="post">
            <h2 class="title"><a href="#">Phasellus pellentesque turpis </a></h2>
            <p class="meta">Posted by <a href="#">Someone</a> on May 01, 2012
              &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
            <div class="entry">
              <p><img src="<?php echo $this->basePath(); ?>/IvelinaVelcheva/images/pics03.jpg" width="200" height="200" alt="" class="alignleft border" />Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc.</p>
            </div>
          </div>
          <div style="clear: both;">&nbsp;</div>
        </div>
        <!-- end #content -->
        <div id="sidebar">
          <ul>
            <li>
              <h2>Aliquam tempus</h2>
              <p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper consectetuer hendrerit.</p>
            </li>
            <li>
              <h2>Categories</h2>
              <ul>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Consectetuer adipiscing elit</a></li>
                <li><a href="#">Metus aliquam pellentesque</a></li>
                <li><a href="#">Suspendisse iaculis mauris</a></li>
                <li><a href="#">Urnanet non molestie semper</a></li>
                <li><a href="#">Proin gravida orci porttitor</a></li>
              </ul>
            </li>
            <li>
              <h2>Blogroll</h2>
              <ul>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Consectetuer adipiscing elit</a></li>
                <li><a href="#">Metus aliquam pellentesque</a></li>
                <li><a href="#">Suspendisse iaculis mauris</a></li>
                <li><a href="#">Urnanet non molestie semper</a></li>
                <li><a href="#">Proin gravida orci porttitor</a></li>
              </ul>
            </li>
            <li>
              <h2>Archives</h2>
              <ul>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Consectetuer adipiscing elit</a></li>
                <li><a href="#">Metus aliquam pellentesque</a></li>
                <li><a href="#">Suspendisse iaculis mauris</a></li>
                <li><a href="#">Urnanet non molestie semper</a></li>
                <li><a href="#">Proin gravida orci porttitor</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- end #sidebar -->
        <div style="clear: both;">&nbsp;</div>
      </div>
    </div>
  </div>
  <!-- end #page -->
</div>
<div id="footer">
  <p>Copyright (c) 2012 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">FCT</a>.</p>
</div>
<!-- end #footer -->
</body>
</html>
