<h1>I am the index.phtml in StudentBg module</h1>

              <h2>
                Welcome to Eponymous
              </h2>
              <img class="left" src="<?php echo $this->basePath();?>/StudentBg/images/pic2.jpg" width="170" height="140" alt="" />
              <p>
                This is <strong>Eponymous</strong>, a two column CSS template by
                <a href="http://www.freecsstemplates.org/">FCT</a> with photos from 
                <a href="http://www.pdphoto.org/">PDPhoto</a>. It's released (for free) under the
                <a href="http://www.freecsstemplates.org/license/">Creative Commons Attribution 3.0 license</a>,
                so feel free to use it for any personal or commercial work, just keep our footer credit links intact.
                Hit up our <a href="http://www.freecsstemplates.org/">website</a> for more awesomely
                cool free templates, and follow us on <a href="http://twitter.com/freecsstemplate">Twitter</a>
                (<a href="http://twitter.com/freecsstemplate">@freecsstemplate</a>) for updates, announcements, and other
                interesting ramblings.
              </p>