<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Old Stairwell 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130313

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Old Stairwell</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet" type="text/css">
  <link href="<?php echo $this->basePath(); ?>/RallNic/css/default.css" rel="stylesheet" type="text/css" media="all" />
<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<div id="wrapper">
  <div id="header">
    <div id="logo">
      <h1><a href="#">Old Stairwell</a></h1>
      <p>Template Design by <a href="http://www.freecsstemplates.org">FCT</a></p>
    </div>
    <div id="menu">
      <ul>
        <li><a href="#" accesskey="1" title="">Homepage</a></li>
        <li><a href="#" accesskey="2" title="">Our Clients</a></li>
        <li><a href="#" accesskey="3" title="">About Us</a></li>
        <li><a href="#" accesskey="4" title="">Careers</a></li>
        <li><a href="#" accesskey="5" title="">Contact Us</a></li>
      </ul>
    </div>
  </div>
  <div id="page">
    <div id="content">
      <h2>Praesent scelerisque scelerisque</h2>
      <p><img src="<?php echo $this->basePath(); ?>/RallNic/images/img02.jpg" width="750" height="250" alt="" /></p>
      <?php echo $this->content; ?>
    </div>
    <div id="sidebar">
      <div id="tbox1">
        <h2>Mauris vulputate dolor</h2>
        <ul class="style2">
          <li class="first">
            <h3><a href="#">Maecenas luctus lectus</a></h3>
            <p><a href="#">Quisque dictum integer nisl risus, sagittis convallis, rutrum id, congue, and nibh.</a></p>
          </li>
          <li>
            <h3><a href="#">Integer gravida nibh</a></h3>
            <p><a href="#">Quisque dictum integer nisl risus, sagittis convallis, rutrum id, congue, and nibh.</a></p>
          </li>
          <li>
            <h3><a href="#">Fusce ultrices fringilla</a></h3>
            <p><a href="#">Quisque dictum integer nisl risus, sagittis convallis, rutrum id, congue, and nibh.</a></p>
          </li>
          <li>
            <h3><a href="#">Nulla luctus eleifend</a></h3>
            <p><a href="#">Quisque dictum integer nisl risus, sagittis convallis, rutrum id, congue, and nibh.</a></p>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div id="three-column">
    <div id="tbox1">
      <h2>Praesent mattis</h2>
      <p>Pellentesque viverra vulputate enim. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit.</p>
      <p><a href="#" class="button-style">Read More</a></p>
    </div>
    <div id="tbox2">
      <h2>Praesent condimentum</h2>
      <ul class="style1">
        <li class="first"><a href="#">Pellentesque consectetuer gravida blandit.</a></li>
        <li><a href="#">Lorem consectetuer adipiscing elit.</a></li>
        <li><a href="#">Maecenas vitae vitae feugiat eleifend.</a></li>
      </ul>
      <p><a href="#" class="button-style">Read More</a></p>
    </div>
    <div id="tbox3">
      <h2>Social</h2>
      <ul class="style1">
        <li class="first"><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Flickr</a></li>
        <li><a href="#">Google +</a></li>
      </ul>
    </div>
  </div>
  <div id="footer">
    <p>Copyright (c) 2013 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org">FCT</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
  </div>
</div>
</body>
</html>
