<?php
echo '<h1 style="background:red; padding: 15px; text-align: center; color: white;">I am in add.phtml GraceDrops Controller</h1>';
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('fmi/default', array('controller' => 'miroslav-garigov', 'action' => 'add'))); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();