<div id="location">nikola-vasilev / delete.phtml</div><br/>
<?php
    $title = 'Delete user';
    $this->headTitle($title);
?>
<div id="content">
  <div id="content2">
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p class="center">Are you sure that you want to delete user 
    '<?php echo $this->escapeHtml($user->getUsrName()); ?>' with password
    '<?php echo $this->escapeHtml($user->getUsrPassword()); ?>'?
</p>
<?php
$url = $this->url('fmi/default', array(
    'controller' => 'nikola-vasilev',
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post" class="center">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $user->getUsrId(); ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
<br/>
<p>
  <a href="<?php echo $this->url('fmi/default', array('controller' => 'nikola-vasilev', 'action'=>'index'));?>">Back to My users</a>
</p>
<br/>
  </div>
</div>
<br/>