<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<?php
echo '<h1>I am in add.phtml CsnCms CommentController</h1>';
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('csn-cms/default', array('controller' => 'comment', 'action' => 'add'), true)); //'contact/process'));
// or
// $form->setAttribute('action', $this->url('grace-drops/default', array('controller' => 'translation', 'action' => 'add', 'id' => $this->id))); //'contact/process'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();