<?php
echo '<h1>I am in edit.phtml CsnCms Controller</h1>';

$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('csn-cms/default', array('controller' => 'comment', 'action' => 'edit', 'id2' => $this->id), true)); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();