<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

  Design by Free CSS Templates
  http://www.freecsstemplates.org
  Released for free under a Creative Commons Attribution License

  Name       : Reverse Obscurity
  Version    : 1.0
  Released   : 20130222

-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Margarita Krushkova</title>
        <link href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css" />
      <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/MargaritaKrushkova/css/style.css" />
    </head>
    <body>
    <div id="bg">
      <div id="outer">
        <div id="header">
          <div id="logo">
            <h1>
              <a href="#">Margarita Krushkova</a>
            </h1>
          </div>
          <div id="nav">
            <ul>
              <li class="first active">
                <a href="#">Home</a>
              </li>
              <li>
                <a href="#">Services</a>
              </li>
              <li>
                <a href="#">Portfolio</a>
              </li>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Links</a>
              </li>
              <li>
                <a href="#">Downloads</a>
              </li>
              <li>
                <a href="#">Blog</a>
              </li>
              <li class="last">
                <a href="#">Contact</a>
              </li>
            </ul>
            <br class="clear" />
          </div>
        </div>
        <div id="banner">
          <img src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/pic1.jpg" width="1124" height="212" alt="magicalforest" />
                    <img class="feq" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/feq.png" width="222" height="280" alt="fairy" />
                     <img class="knight" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/knight.png" width="200" height="295" alt="fairy" />
        </div>
        <div id="main">
          <div id="sidebar1">
            <h3>
              Pharetra sodales egestas
            </h3>
            <p>
              Enim amet sociis ullamcorper lorem ligula. Viverra odio massa sapien et augue lacus pretium. 
              Sociis magna faucibus dictum curabitur auctor et molestie proin sed aliquam.
            </p>
            <h3>
              Venenatis elementum porttitor
            </h3>
            <ul class="linkedList">
              <li class="first">
                <a href="#">Varius nulla fusce suscipit</a>
              </li>
              <li>
                <a href="#">Rutrum orci amet et lorem</a>
              </li>
              <li>
                <a href="#">Convallis sodales malesuada</a>
              </li>
              <li>
                <a href="#">Faucibus imperdiet adipiscing</a>
              </li>
              <li>
                <a href="#">Diam porta at sed tortor</a>
              </li>
              <li>
                <a href="#">Rutrum orci amet et lorem</a>
              </li>
              <li>
                <a href="#">Convallis sodales malesuada</a>
              </li>
              <li>
                <a href="#">Faucibus imperdiet adipiscing</a>
              </li>
              <li class="last">
                <a href="#">Dictum in amet phasellus</a>
              </li>
            </ul>
          </div>
          <div id="sidebar2">
            <h3>
              Dictum sed montes
            </h3>
            <ul class="linkedList">
              <li class="first">
                <a href="#">Euismod parturient dolor</a>
              </li>
              <li>
                <a href="#">Malesuada dignissim aenean</a>
              </li>
              <li>
                <a href="#">Felis amet condimentum</a>
              </li>
              <li>
                <a href="#">Duis rutrum urna congue</a>
              </li>
              <li>
                <a href="#">Iaculis etiam sed nibh</a>
              </li>
              <li class="last">
                <a href="#">Metus dolor et consequat</a>
              </li>
            </ul>
            <h3>
              Nulla parturient tortor
            </h3><img class="top" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/pic1.jpg" width="232" height="84" alt="" />
            <p>
              Facilisis risus tortor elit scelerisque integer nascetur. Magnis lacus arcu erat gravida diam lorem et posuere. 
              Aliquam proin nisl mus ultrices morbi consequat veroeros dolore.
            </p>
          </div>
          <div id="content">
            <div id="box1">
              <?php echo $this->content; ?>
              <h2>
                Welcome to Reverse Obscurity
              </h2><img class="left" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/pic2.jpg" width="100" height="115" alt="" />
              <p>
                This is <strong>Reverse Obscurity</strong>, a three column CSS template by
                <a href="http://www.freecsstemplates.org/">FCT</a> with photos from 
                <a href="http://www.pdphoto.org/">PDPhoto</a>. It's released (for free) under the
                <a href="http://www.freecsstemplates.org/license/">Creative Commons Attribution 3.0 license</a>,
                so feel free to use it for any personal or commercial work, just keep our footer credit links intact.
                Hit up our <a href="http://www.freecsstemplates.org/">website</a> for more awesomely
                cool free templates, and follow us on <a href="http://twitter.com/freecsstemplate">Twitter</a>
                (<a href="http://twitter.com/freecsstemplate">@freecsstemplate</a>) for updates, announcements, and other
                mildly interesting ramblings.
              </p>
            </div>
            <div id="box2">
              <h3>
                Pulvinar quis pellentesque
              </h3>
              <p>
                Tempor sociis nullam proin placerat velit volutpat auctor. Fermentum et et eleifend molestie urna.
              </p>
              <ul class="linkedList">
                <li class="first">
                  <a href="#">Quisque vulputate faucibus</a>
                </li>
                <li>
                  <a href="#">Neque aliquam vitae nisi</a>
                </li>
                <li>
                  <a href="#">Odio sagittis montes massa</a>
                </li>
                <li>
                  <a href="#">Curabitur euismod condimentum</a>
                </li>
                <li class="last">
                  <a href="#">Imperdiet placerat mi ornare</a>
                </li>
              </ul>
            </div>
            <div id="box3">
              <h3>
                Quis curae accumsan placerat
              </h3>
              <ul class="imageList">
                <li class="first">
                  <img class="left" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/pic2.jpg" width="60" height="60" alt="" /> <span>Commodo proin lacinia blandit aenean orci penatibus.</span>
                </li>
                <li>
                  <img class="left" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/pic2.jpg" width="60" height="60" alt="" /> <span>Nulla elit parturient eleifend aenean dictum proin.</span>
                </li>
                <li class="last">
                  <img class="left" src="<?php echo $this->basePath();?>/MargaritaKrushkova/images/pic2.jpg" width="60" height="60" alt="" /> <span>Feugiat ut ut lectus cubilia faucibus condimentum.</span>
                </li>
              </ul>
            </div>
            <br class="clear" />
          </div>
          <br class="clear" />
        </div>
        <div id="footer">
          <div id="footerContent">
            <h3>
              Odio cum elit orci
            </h3>
            <p>
              Fusce fringilla faucibus eget nibh congue. Cubilia velit blandit mus accumsan hendrerit tortor. Nisi orci 
              sollicitudin faucibus. Ipsum egestas rhoncus volutpat sollicitudin. Elementum magnis varius risus sem et 
              auctor aliquet. Dictum parturient viverra convallis purus montes cubilia augue. Feugiat tortor ac velit 
              purus felis. Convallis mollis varius consequat. Dictum parturient et viverra sed convallis purus montes cubilia 
              augue. Feugiat tortor ac velit purus felis. Convallis mollis varius consequat. Cubilia velit blandit mus 
              accumsan hendrerit tortor. Nisi orci sollicitudin faucibus lorem ipsum dolor sit amet dolore.
            </p>
          </div>
          <div id="footerSidebar">
            <h3>
              Sollicitudin iaculis
            </h3>
            <ul class="linkedList">
              <li class="first">
                <a href="#">Cras pharetra amet</a>
              </li>
              <li>
                <a href="#">Praesent turpis</a>
              </li>
              <li class="last">
                <a href="#">Augue laoreet pellentesque</a>
              </li>
            </ul>
          </div>
          <br class="clear" />
        </div>
      </div>
      <div id="copyright">
        &copy; Margarita Krushkova | Design by <a href="http://www.freecsstemplates.org/">FCT</a>
      </div>
    </div>
    </body>
</html>
