<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/MartinManov/css/styles.css">
<title>Sample</title>
</head>

<body>
<header>
  <h1>MAIN TITLE</h1>  
  <nav>
    <ul>
      <li><a href="#" target="_parent">Nav 1</a></li>
      <li><a href="#" target="_parent">Nav 2</a></li>
      <li><a href="#" target="_parent">Nav 3</a></li>
      <li><a href="#" target="_parent">Nav 4</a></li>
    </ul>
  </nav>
</header>
  
  
  <section id="left">
    <h1>Links</h1>
    <ul>
      <li><a href="#">Link 1</a></li>
      <li><a href="#">Link 2</a></li>
      <li><a href="#">Link 3</a></li>
      <li><a href="#">Link 4</a></li>
    </ul>
  </section>
  
  <article>
    <h1>Content</h1>
    <?php echo $this->content; ?>
  </article>

</body>

</html>