<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Cafe and Bakery | Free CSS Template</title>
<meta name="keywords" content="Cafe and Bakery, Free CSS Template, Pink, Black" />
<meta name="description" content="Cafe and Bakery is a free CSS template using pink gradient and black colors." />
<link href="templatemo_style.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="css/coda-slider.css" type="text/css" charset="utf-8" />

<script src="js/jquery-1.2.6.js" type="text/javascript"></script>
<script src="js/jquery.scrollTo-1.3.3.js" type="text/javascript"></script>
<script src="js/jquery.localscroll-1.2.5.js" type="text/javascript" charset="utf-8"></script>
<script src="js/jquery.serialScroll-1.2.1.js" type="text/javascript" charset="utf-8"></script>
<script src="js/coda-slider.js" type="text/javascript" charset="utf-8"></script>
<script src="js/jquery.easing.1.3.js" type="text/javascript" charset="utf-8"></script>

</head>
<body>

<div id="slider">
	<div id="templatemo_wrapper">

		<div id="templatemo_social">
        
        </div> <!-- end of social -->
        
        <div id="templatemo_main">
        	<div id="templatemo_sidebar">
            	<div id="header"><h1><a href="http://www.templatemo.com">Cafe and Bakery</a></h1></div>
                
                <div id="menu">
                    <ul class="navigation">
                    <li><a href="#home" class="selected">Home</a></li>
                    <li><a href="#aboutus">About Us</a></li>
                    <li><a href="#services">Services</a></li>
                    <li><a href="#blog">Our Blog</a></li>
                    <li><a href="#contactus" class="last">Contact Us</a></li>
                    </ul>
                </div>
            </div> <!-- end of sidebar -->
            
            <div id="templatemo_content">
            	<div class="scroll">
	        		<div class="scrollContainer">
                    
                    <div class="panel" id="home">
                        <h2>Welcome to Cafe and Bakery</h2>   
                        
                        <p><em>Nullam at erat ipsum, quis tincidunt mauris. Nunc sit amet sapien eget eros iaculis hendrerit quis a enim.</em></p>	
                        <a href="http://www.templatemo.com/page/1" target="_parent"><img src="images/templatemo_image_01.jpg" alt="Image 1" class="image_wrapper image_fl" /></a>        
                        
                      <p align="justify">Cafe &amp; Bakery website template is provided by <a href="http://www.templatemo.com" target="_parent">templatemo.com</a> for everyone. Validate <a href="http://validator.w3.org/check?uri=referer" rel="nofollow">XHTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow">CSS</a>. You may download, modify and apply this template for your websites. Credits go to <a href="http://www.photovaco.com" target="_blank">Free Photos</a> for photos. Morbi rutrum euismod elit, nec adipiscing ante sodales sed.</p>

                        <div class="cleaner cleaner_h40"></div>
                        <h3>Lorem ipsum dolor</h3>
                        
                        <ul class="tmo_list">
                            <li><a href="#" class="service_one">Aliquam auctor odio sit amet felis laoreet a consequat sapien porttitor.</a></li>
                            <li><a href="#" class="service_two">Vestibulum eros nisi, lobortis ac pulvinar at, sagittis non felis. </a></li>
                            <li><a href="#" class="service_three">Suspendisse viverra elementum dui, sit amet tempor ante mollis sit amet.</a></li>
                            <li><a href="#" class="service_four">Proin malesuada rutrum sem et consequat. Maecenas et nunc sed leo faucibus cursus et sed diam. </a></li>    
                        </ul>
                    </div>
                    <!-- end of home -->
                    
                    <div class="panel" id="aboutus">
                        <h2>About Us</h2>
                       
                        <a href="http://www.templatemo.com/page/2" target="_parent"><img src="images/templatemo_image_01.jpg" alt="Image 2" class="image_wrapper image_fr" /></a>
                        <p><em>Lorem ipsum dolor sit amet, consec tetur adipiscing elit. Suspendisse in lectus turpis.</em></p>
                        <p>Lorem ipsum dolor sit amet, consec tetur adipiscing elit. Cras vene natis nulla ac mi solli citudin vul putate. Etiam blandit mi sed urna iaculis vitae vehicula nisl <a href="#">facilisis</a>. Aliquam vitae erat sit amet dolor hend rerit pellen tesque.  Nullam sit amet purus turpis, vitae lobortis nisi.</p>
                        <p>Nullam sit amet purus turpis, vitae lobortis nisi. Pellentesque pellentesque rutrum est, vel feugiat <a href="#">nulla congue</a> sit amet. Ut ultricies aliquet mauris ultrices posuere. </p>

                        <div class="cleaner cleaner_h40"></div>
                        <h3>Message from the founder</h3>
                        <blockquote>
                        <p>Fusce nec felis id lacus sollicitudin vulputate. Proin tincidunt, arcu id pellentesque accumsan, neque dolor imperdiet ligula, quis viverra tellus nulla a odio. Curabitur vitae enim risus, at placerat turpis. Mauris feugiat suscipit tempus fringilla, felis in velit.</p>
                        <cite>William - <span>CEO</span></cite> </blockquote>
                    </div> <!-- end of about us -->
                    
                    <div class="panel" id="services">
                        <h2>Our Services</h2>
                         <img src="images/templatemo_image_01.jpg" alt="Image" class="image_wrapper image_fr" />
                        <p><em>Nam at arcu libero, ut venenatis elit. Nulla eget risus turpis, non aliquet dui.</em></p>
                        <p>Donec fringilla egestas ante, vel <a href="#">euismod</a> mi venenatis et. Ut molestie porta urna, vitae tempor tellus mollis at. Proin tincidunt luctus ipsum, quis volutpat neque iaculis sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin a neque et <a href="#">felis suscipit</a> scelerisque a eget enim.</p>

						<div class="cleaner cleaner_h40"></div>
                        <h3>Service List</h3>
                        <ul class="tmo_list">
                            <li><a href="#" class="service_one">Aliquam auctor odio sit amet felis laoreet a consequat sapien porttitor.</a></li>
                            <li><a href="#" class="service_two">Vestibulum eros nisi, lobortis ac pulvinar at, sagittis non felis. </a></li>
                            <li><a href="#" class="service_three">Suspendisse viverra elementum dui, sit amet tempor ante mollis sit amet.</a></li>
                            <li><a href="#" class="service_four">Proin malesuada rutrum sem et consequat. Maecenas et nunc sed leo faucibus cursus et sed diam. </a></li>
						</ul>
                    </div> <!-- end of services -->
                    
                    <div class="panel" id="blog">
                        <div class="post_box">
                            <h2><a href="#">Lorem ipsum dolor sit amet</a></h2>
                            <img src="images/templatemo_image_02.jpg" class="image_wrapper" alt="Image 2" />
                            <p><span class="cat">Posted in <a href="#">Templates</a>, <a href="#">Design</a></span> | <a href="#">36 comments</a></p>
                            <p>Vestibulum adipiscing tempus elit eu condimentum. Fusce at mi felis. Etiam sed velit nibh.</p>
                            <a class="more float_r" href="#">More</a>
                            <div class="cleaner"></div>
                        </div>
                        <div class="post_box">
                            <h2><a href="#">Cum Sociis Natoque Penatibus</a></h2>
                            <img src="images/templatemo_image_03.jpg" class="image_wrapper" alt="Image 3" />
                            <p><span class="cat">Posted in <a href="#">Social</a>, <a href="#">Web</a></span> | <a href="#">12 comments</a></p>
                            <p>Vestibulum adipiscing tempus elit eu condimentum. Fusce at mi felis. Etiam sed velit nibh.</p>
                            <a class="more float_r" href="#">More</a>
                        </div>
                        <div class="post_box">
                            <h2><a href="#">Etiam Auctor Sapien Dapibus</a></h2>
                            <img src="images/templatemo_image_04.jpg" class="image_wrapper" alt="Image 4" />
                            <p><span class="cat">Posted in <a href="#">SEO</a>, <a href="#">Analytics</a></span> | <a href="#">24 comments</a></p>
                            <p>Vestibulum adipiscing tempus elit eu condimentum. Fusce at mi felis.</p>
                             <a class="more float_r" href="#">More</a>
                            <div class="cleaner"></div>
                        </div>
                        
                    </div> <!-- end of gallery -->
                    
                    <div class="panel" id="contactus">
                    	<h2>Contact Us</h2>
                        <p>Proin malesuada rutrum sem et consequat. Maecenas et nunc sed leo faucibus cursus et sed diam. Fusce at mi felis. Etiam sed velit nibh.</p>
                        <h5>Mailing Address</h5>
                        111-333 Duis lacinia dictum, <br />
                        PVestibulum auctor, 10113<br />
                        Nam rhoncus, diam a mollis tempor<br />
                        Tel: 010-020-0340
                        
                        <div class="cleaner cleaner_h40"></div>
                        
                        <div id="contact_form">
                            <form method="post" name="contact" action="#">
                                <input type="hidden" name="post" value="Send" />
                                <label for="author2">Name:</label>
                                <input type="text" id="author2" name="author" class="required input_field" />
                                <div class="cleaner_h10"></div>
                                <label for="email">Email:</label>
                                <input type="text" id="email" name="email" class="validate-email required input_field" />
                                <div class="cleaner_h10"></div>
                                <label for="text">Message:</label>
                                <textarea id="text" name="text" rows="0" cols="0" class="required"></textarea>
                                <div class="cleaner_h10"></div>
                                <input type="submit" class="submit_btn float_l" name="submit" id="submit" value=" Send " />
                                <input type="reset" class="submit_btn float_r" name="reset" id="reset" value=" Reset " />
                            </form>
                        </div>
                        
                    </div> <!-- end of contact us -->
                    
                    </div> <!-- end scrollContainer -->
				</div>
            </div> <!-- end of content -->
            
            <div class="cleaner">s</div>
        </div> <!-- end of main -->
    
    	
        <div id="templatemo_footer">
        
           	Copyright © 2048 <a href="#">Your Company Name</a><br />
    		Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>
            
            <div class="cleaner"></div>
		</div>       
        
    </div> <!-- end of wrapper -->
</div> <!-- end of slider -->

</body>
</html>