<h1>Index = Retrieve</h1>
<a href="<?php echo $this->url('csn_user/default', array('controller' => 'user-doctrine-paginator', 'action' => 'create')); ?>">Create</a>
<table class="table">
<tr>
	<th>usr_id</th>
	<th>usr_name</th>
	<th>usr_email</th>
</tr>
<?php
	foreach ($paginator as $row) {
?>
		<tr>
			<td><?php  echo $row->getUsrId(); ?></td>
			<td><?php  echo $row->getUsrName(); ?></td>
			<td><?php  echo $row->getUsrEmail(); ?></td>
			<td><a href="<?php echo $this->url('csn_user/default', array('controller' => 'user-doctrine-paginator', 'action' => 'update', 'id' => $row->getUsrId())); ?>">Edit</a></td>
			<td><a href="<?php echo $this->url('csn_user/default', array('controller' => 'user-doctrine-paginator', 'action' => 'delete', 'id' => $row->getUsrId()));?>" onclick="return confirm('Do you rely want to delete the record?')">Delete</a></td>
		</tr>
<?php
	}
?>
</table>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', // All, Elastic, Jumping, Sliding
                                    'search_pagination.phtml', array('route' => 'csn_user/paginator-doctrine')); ?>
<!-- 'search_pagination.phtml' 'item_pagination.phtml' dropdown_pagination.phtml -->
<!-- ToDo, 'controller' => 'user-doctrine-paginator', array('controler'=>'user-doctrine-paginaytor') -->