<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Explore California Trail Guide</title>
<!--update based on html5-->
<link href="file:///E|/Downloads/Lynda.com - Dreamweaver CS5 Getting Started with HTML5/Exercise Files/Ex_Files_DWCS5_HTML5/Ex_Files_DWCS5_HTML5/Exercise Files/Chapter 3/03_01/_css/main.css" rel="stylesheet" type="text/css">
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>
<div id="wrapper">
<header id="mainHeader">

<img src="DINKA.jpg" width="1100" height="600" alt="Dinka" />
    <nav id="mainNav">
    <h1>Main page navigation</h1>
   <ul id="MenuBar1" class="sf-menu sf-js-enebled">
    <li><a class="home" href="#">Home</a>
     
    </li>
    <li><a class="about" href="#">About </a>
    </li>
    <li><a class="music" href="#">Music</a>
    </li>
     <li><a class="events"href="#">Events</a></li>
    <li><a class="blog" href="#">Blog</a></li>
     <li class="last3"><a  href="#">Contacts</a></li>
  </ul>
  </nav>
</header>
  <section id="trailInfo">
 <header>
    
      </header>
      <article>
      <h1>Northridge Loop</h1>
    <table id="quickFacts" cellspacing="0">
   
      <tr>
        <th>trail status:</th>
        <td><span class="open">all trails open</span></td>
      </tr>
      <tr class="alt">
        <th>trail type:</th>
        <td>single track</td>
      </tr>
      <tr>
        <th>elevation:</th>
        <td>2000 ft</td>
      </tr>
      <tr class="alt">
        <th>length:</th>
        <td>14.5 miles</td>
      </tr>
      <tr>
        <th>skill level:</th>
        <td>beginner to intermediate</td>
      </tr>
    </table>
    <div class="text2Col">
<p>If you are looking for great scenery and a great workout without all the technical difficulty of other trails, Northridge Loop is for you. The ridge runs east to west, with Ojai Valley on one side and Rose Valley on the other. The trail features amazing views of both valleys plus the Los Padres National Forest. </p>
    <p>There are a total of 6 trail heads spread out over the 14.5 mile loop, so there are plenty of places to get on or off the trail. Hiking is permitting along all trails, so make sure you ride with caution and don't override your stopping power.</p>
    <h2>Skill level</h2>
    <p>While the overall trail is fine for beginners, two of the trail spurs, Gridley and Pratt, are much narrower and technical, so be sure to check the signage before choosing a trail. </p>
    <p>While there are no steep drops or bombs on this trail, there are several areas of the trail that extend over bare rock. The paths are marked, but there are canyon areas that you should be aware of. Before starting any downhill section make sure you know the path!</p>
    <h2>Surface</h2>
    <p>Most of the lower trails are firebreak roads or other, wide access roads. As you climb, trails become single track and a bit more technical. There are patches of bare rock and loose rock is common on most downhill sections. If you choose to ascend via the Killabase Road trail head, the first quarter mile is mixture of paved path and gravel.</p>
    <img src="dinkaSmall.jpg" alt="dinka" width="519" height="613" />
</div>
    </article>
  </section>
  <aside id="trailNews">
    <h1>Trail News</h1>
    <article class="news">
      <header>
      <hgroup>
        <h1>Rider Reviews</h1>
        <h2>Los Robles Trail</h2>
         <h3>by Justin Vyn</h3>
         </hgroup>
          <p class="pubdate">submitted on
            <time datetime="2010-02-10" pubdate>02/23/10</time>
          </p>     
      </header>
     <p>My buddies and I had heard about this trail in November from a friend who had finished the West portion earlier in the month. It sounded like a good trail, but we didn't have time to check it out until last week.</p>
     <p>All I can say is wow! I really hate that I waited so long to try this trail, especially since it's right in my backyard (I live in Ventura).
       My friends and I got to the first trail head around 9:30 am that morning. The first portion of the trail were firebreaks and service roads, and for a while it seemed that we were just going to be going on another scenic ride.</p>
     <p>About two-thirds of the way up, we came to the first set of single-tracks breaking away from the firebreak. From then on the trail did not let up!</p>
     <p>Heavy on switchbacks (both on the climb and on the descent), and with good climbs, the trail alone is worth the trip! However, towards the top, we encountered a pretty strong technical section. Bare rock, small washouts, and loose rocks made for some slow going in areas. </p>
     <p>On the descent, the more technical nature of the trail keeps you from bombing out a run. A friend of mine that doesn't wish to be named (we'll call him Marty) is just starting out and we may have pushed him a bit too much! After the exhausting climb he didn't have much left for the downhill. He took two tumbles on the way down but thankfully wasn't hurt bad.</p>
     <p>Hitting the firebreaks again on the way down isn't a bad thing either. You can pick your speed up a bit here, and there are a few shallow hills that allow you to get some really good air.</p>
     <p>For this trip we just did the West trail. I'm really looking forward to going back in a few weeks to do the East trail as well!</p>
     <div id="formPanel">
    <p class="review">Write your own review!</p>
      <form id="riderReview" method="post" action="#">
      <label for="trailName">Trail name:</label>
          <input type="text" name="name" id="name" tabindex="10"  placeholder="trail name" required>
          <label for="name">Name:</label>
          <input type="text" name="name" id="name" tabindex="20"  placeholder="first and last name" required>
          <label for="email">Email:</label>
          <input type="email" name="email" id="email" tabindex="30" placeholder="valid email address"  required>
          <label for="url">Website:</label>
          <input type="url" name="url" id="url" tabindex="40">
          <label for="tripDate">Date of trip:</label>
          <input type="date" name="tripDate" id="tripDate" tabindex="50">
          <label for="riders">Number of riders:</label>
          <input type="number" name="riders" id="riders" tabindex="60" min="1" value="1" >
          <label for="review">Review:<br>
          </label>
          <textarea name="review" id="review" tabindex="70" cols="45" rows="10"></textarea>
          <input type="submit" name="submit" id="submit" tabindex="80" value="Submit your review">
      </form>
    </div>
    </article>
  </aside>
  <footer id="pageFooter">
  <p>&copy;copyright 2011 Explore California.org</p>
  <p><a href="#">legal</a> | <a href="#">privacy</a> </p>
  </footer>
</div>
</body>
</html>
