
<!DOCTYPE html>
<html lang="en">
<head>
<title>Home</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<link rel="stylesheet" href="css/style.css" type="text/css" media="screen">
<script src="js/jquery-1.7.1.min.js"></script>
<script src="js/script.js"></script>
<script src="js/superfish.js"></script>
<script src="js/jquery.responsivemenu.js"></script>
<script src="js/jquery.flexslider-min.js"></script>
<script src="js/FF-cash.js"></script>
<!--[if lt IE 8]>
   <div style=' clear: both; text-align:center; position: relative;'>
     <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
       <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
    </a>
  </div>
<![endif]-->
<!--[if lt IE 9]>
  <script src="js/html5.js"></script>
  <link rel="stylesheet" href="css/ie.css"> 
<![endif]-->
</head>
<body>
<!-- header -->
<header>
  <div class="container_24">
    <div class="grid_24">
      <h1 class="fleft"><a href="index.html">Glosey</a></h1>
      <ul class="sf-menu">
        <li class="current"><a href="index.html">Home</a></li>
        <li><a href="index-1.html">Company<span class="arrow"></span></a><ul>
            <li><a href="#">History</a></li>
            <li><a href="#">Work Team</a></li>
            <li><a href="#">Profile</a><ul>
                <li><a href="#">Mission</a></li>
                <li><a href="#">Capabilities</a></li>
                <li><a href="#">Support</a></li>
                <li><a href="#">Partnership</a></li>
              </ul>
            </li>
            <li><a href="#">Testimonials</a></li>
          </ul>
        </li>
        <li><a href="index-2.html">Services</a></li>
        <li><a href="index-3.html">Solutions</a></li>
        <li><a href="index-4.html">Projects</a></li>
        <li><a href="index-5.html">Contacts</a></li>
      </ul>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
</header>
<div class="main-slider">
<div class="bg-slider">
  <div class="slider">
    <div class="flexslider">
      <ul class="slides">
        <li><img src="images/slide1.jpg" alt=""><div class=" flex-caption"><span>Our work is dedicated to the prosperity of our clients!</span></div></li>
        <li><img src="images/slide2.jpg" alt=""><div class=" flex-caption"><span>We will show you the way to success!</span></div></li>
        <li><img src="images/slide3.jpg" alt=""><div class=" flex-caption"><span>Our work is dedicated to the prosperity of our clients!</span></div></li>
      </ul>
    </div>
  </div>
</div>
</div>
<!-- content -->
<section>
  <div class="bg">
    <div class="container_24">
      <div class="wrapper">
        <div class="grid_8 padtop3">
          <div class="box-img img1"><img src="images/1page_img1.jpg" alt=""></div>
          <h4 class="padtop">24/7 Online Support</h4>
          <p class="padbot">Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus.</p>
          <a href="#" class="button">More</a>
        </div>
        <div class="grid_8 padtop3">
          <div class="box-img img1"><img src="images/1page_img2.jpg" alt=""></div>
          <h4 class="padtop">Team Leaders</h4>
          <p class="padbot">Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus.</p>
          <a href="#" class="button">More</a>
        </div>
        <div class="grid_8 padtop3">
          <div class="box-img img1"><img src="images/1page_img3.jpg" alt=""></div>
          <h4 class="padtop">Strategic Growth</h4>
          <p class="padbot">Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus.</p>
          <a href="#" class="button">More</a>
        </div>
      </div>
    </div>
  </div>
  <div class="container_24">
    <div class="wrapper">
      <div class="grid_16 padtop2">
        <h4 class="padbot2">Solutions, that you need!</h4>
        <p class="text1 it">Praesent vestibulum molestie lacus. Aenean nmmy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis 
parturient montes, nascetur ridiculus.</p>
        <p class="padbot2">Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit.</p>
        <a href="#" class="button1">Read More</a>
      </div>
      <div class="grid_8 padtop2">
        <h4 class="padbot2">Contact Info</h4>
        <p class="text2">The Company Name Inc.<br>
        8901 Marmora Road,Glasgow,<br>
        D04 89GR.</p>
        <p class="text1">Freephone: +1 800 559 6580<br>
        FAX: +1 504 889 9898<br>
        E-mail: <a href="#">mail@demolink.org</a></p>
        <h4 class="pad">Get in Touch</h4>
        <ul class="icons">
          <li><a href="#"><img src="images/icon1.jpg" alt=""></a></li>
          <li><a href="#"><img src="images/icon2.jpg" alt=""></a></li>
          <li><a href="#"><img src="images/icon3.jpg" alt=""></a></li>
          <li><a href="#"><img src="images/icon4.jpg" alt=""></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- footer -->
<footer>
  <div class="container_24">
    <div class="wrapper">
      <div class="grid_24"><a href="index.html" class="link"><img src="images/logo-footer.png" alt=""></a> &copy; 2012 | <a href="index-6.html">Privacy Policy</a> <!-- {%FOOTER_LINK} --></div>
    </div>
  </div>
</footer>  
</body>
</html>
