<h2>Hi! Welcome to Victor's awesome module!</h2>

<p>This is a short text of my index.phtml file. The site looks nice, coufon font is working flawlessly!</p>

<h3>Services I provide:</h3>
<ul>
	<li><img src="<?php echo $this->basePath();?>/VictorAtanassov/images/icon-print.png" alt="Print Design">Print Design</li>
	<li><img src="<?php echo $this->basePath();?>/VictorAtanassov/images/icon-webdesign.png" alt="Web Design">Web Design</li>
	<li><img src="<?php echo $this->basePath();?>/VictorAtanassov/images/icon-development.png" alt="Development">Development</li>
</ul>