<h1>Registration</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('usrName'));
echo $this->formRow($form->get('usrEmail'));
echo $this->formRow($form->get('usrPassword'));
echo $this->formRow($form->get('usrPasswordConfirm'));
echo $this->formRow($form->get('captcha'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>