<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Illustrative 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20121223

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Illustrative by FCT</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css" />
  <link href="<?php echo $this->basePath(); ?>/VanyaDimitrova/css/default.css" rel="stylesheet" type="text/css" media="all" />
<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<div id="wrapper">
  <div id="header">
    <div id="banner"><img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/header-image-bg2.jpg" width="1200" height="200" alt="" /></div>
    
  </div>
  <!-- end #header -->
  <div id="menu">
    <ul>
      <li class="current_page_item"><a href="#">Home</a></li>
      <li><a href="#">Blog</a></li>
      <li><a href="#">Photos</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Links</a></li>
      <li class="last"><a href="#">Contact</a></li>
    </ul>
  </div>
  <div id="banner"><img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/header-image-bg.jpg" width="1200" height="400" alt="" /></div>
  <div id="three-columns">
    <div class="content">
      <div id="column1">
        <h2>Maecenas luctus</h2>
        <p><img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/pics01.jpg" width="430" height="200" alt="" /></p>
       <?php echo $this->content; ?>
        <p><a href="#" class="link-style">Read More</a></p>
      </div>
      <div id="column2">
        <h2>Fusce fringilla</h2>
        <ul class="list-style1">
          <li class="first">
            <p>Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. </p>
            <p><a href="#" class="link-style">Read More</a></p>
          </li>
          <li>
            <p>Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. </p>
            <p><a href="#" class="link-style">Read More</a></p>
          </li>
          <li>
            <p>Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. </p>
            <p><a href="#" class="link-style">Read More</a></p>
          </li>
        </ul>
      </div>
      <div id="column3">
        <h2>Praesent mattis</h2>
        <ul class="list-style2">
          <li class="first"><a href="#">Vestibulum luctus venenatis dui</a></li>
          <li><a href="#">Integer rutrum nisl in mi</a></li>
          <li><a href="#">Etiam malesuada rutrum enim</a></li>
          <li><a href="#">Aenean elementum facilisis ligula</a></li>
          <li><a href="#">Ut tincidunt elit vitae augue</a></li>
          <li><a href="#">Aenean elementum facilisis ligula</a></li>
          <li><a href="#">Aenean elementum facilisis ligula</a></li>
          <li><a href="#">Aenean elementum facilisis ligula</a></li>
          <li><a href="#">Ut tincidunt elit vitae augue</a></li>
          <li><a href="#">Sed quis odio sagittis leo vehicula</a></li>
        </ul>
        <p><a href="#" class="link-style">Read More</a></p>
      </div>
    </div>
  </div>
  <div id="footer-content">
    <div id="fbox1">
      <h2>Maecenas luctus lectus</h2>
      <ul class="list-style1">
        <li class="first">
          <p class="date">December 24, 2012</p>
          <p> <img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/icon.png" width="130" height="119" alt="" />Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit. Nullam ante orci, pellentesque eget, tempus quis, ultrices in, est. Curabitur sit amet nulla. Nam in massa. Pellentesque viverra vulputate enim. Aliquam erat volutpat. Donec placerat odio vel elit. Pellentesque viverra vulputate enim.</p>
        </li>
        <li>
          <p class="date">December 20, 2012</p>
          <p><img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/icon.png" width="130" height="119" alt="" />Pellentesque viverra vulputate enim. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit. Nullam ante orci, pellentesque eget, tempus quis, ultrices in, est. Suspendisse dictum porta lectus. Pellentesque viverra vulputate enim.</p>
        </li>
      </ul>
    </div>
    <div id="fbox2">
      <h2>Nulla  eleifend</h2>
      <p><img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/list-image-01.jpg" width="220" height="150" alt="" /></p>
      <p>Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit. Pellentesque viverra vulputate enim. Aliquam erat volutpat. </p>
      <p><a href="#" class="link-style">Read More</a></p>
    </div>
    <div id="fbox3">
      <h2>Fusce  fringilla</h2>
      <p><img src="<?php echo $this->basePath(); ?>/VanyaDimitrova/images/list-image-02.jpg" width="220" height="150" alt="" /></p>
      <p>Donec placerat odio vel elit. Nullam ante orci, pellentesque eget, tempus quis, ultrices in, est. Curabitur sit amet nulla. Nam in massa. Pellentesque viverra vulputate enim. Aliquam erat volutpat.  Aliquam erat volutpat. </p>
      <p><a href="#" class="link-style">Read More</a></p>
    </div>
  </div>
</div>
<div id="footer">
  <p>Copyright (c) 2012 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org">FCT</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>  + <a href="http://iconify.it/">Iconify.it</a></p>
</div>
</body>
</html>
