<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

  Design by Free CSS Templates
  http://www.freecsstemplates.org
  Released for free under a Creative Commons Attribution License

  Name       : Null Atmosphere
  Version    : 1.0
  Released   : 20130222

-->
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Null Atmosphere by FCT</title>
    <link href="http://fonts.googleapis.com/css?family=Bitter" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/NikolaiBaldjiev/css/style.css" />
  </head>
  <body>
    <div id="outer">
      <div id="header">
        <div id="logo">
          <h1>
            <a href="#">Null Atmosphere</a>
          </h1>
        </div>
        <div id="nav">
          <ul>
            <li class="first active">
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#">Blog</a>
            </li>
            <li>
              <a href="#">Services</a>
            </li>
            <li>
              <a href="#">Portfolio</a>
            </li>
            <li class="last">
              <a href="#">Contact</a>
            </li>
          </ul>
          <br class="clear" />
        </div>
      </div>
      <div id="main">
        <div id="content">
          <div id="box1">
            <img class="left" src="<?php echo $this->basePath(); ?>/NikolaiBaldjiev/images/pic1.jpg" width="120" height="140" alt="" />
              <?php echo $this->content; ?>
          </div>
          <div id="box2">
            <h3>
              Tincidunt augue morbi
            </h3>
            <p>
              Nulla penatibus cubilia metus tortor tristique malesuada sollicitudin. Fusce gravida venenatis 
              tristique ultrices. Faucibus mus morbi mattis orci suscipit auctor. Arcu blandit ultricies odio.
              Eleifend sociis donec quis. Condimentum eleifend nec felis nec ullamcorper luctus.
            </p>
            <ul class="linkedList">
              <li class="first">
                <a href="#">Cubilia sem purus porta felis mollis lorem ipsum</a>
              </li>
              <li>
                <a href="#">Lacinia nisi magna fringilla purus condimentum mattis</a>
              </li>
              <li>
                <a href="#">Fusce feugiat vulputate augue amet commodo felis nullam</a>
              </li>
              <li>
                <a href="#">Tincidunt molestie phasellus hendrerit aenean suspendisse malesuada veroeros consequat lorem</a>
              </li>
              <li class="last">
                <a href="#">Nisi cursus curabitur velit porttitor montes veroeros etiam iaculis etiam tempus lorem ipsum</a>
              </li>
            </ul>
          </div>
          <br class="clear" />
        </div>
        <div id="sidebar1">
          <h3>
            Praesent volutpat pharetra
          </h3>
          <p>
            Nullam semper rhoncus vivamus phasellus massa malesuada. Vitae at tristique urna odio augue tempus quam. Nibh dis volutpat nascetur lacinia.
          </p>
          <ul class="linkedList">
            <li class="first">
              <a href="#">Consectetur accumsan morbi penatibus</a>
            </li>
            <li>
              <a href="#">Curabitur magna mattis cras</a>
            </li>
            <li class="last">
              <a href="#">Volutpat fusce odio</a>
            </li>
          </ul>
          <h3>
            Faucibus posuere
          </h3>
          <div class="dateList">
            <ul class="linkedList dateLinkedList">
              <li class="first">
                <span class="date">Dec 5</span> <a href="#">Fermentum rutrum</a>
              </li>
              <li>
                <span class="date">Dec 4</span> <a href="#">Consectetur porttitor</a>
              </li>
              <li>
                <span class="date">Dec 2</span> <a href="#">Elementum diam</a>
              </li>
              <li>
                <span class="date">Nov 28</span> <a href="#">Sed amet et etiam</a>
              </li>
              <li>
                <span class="date">Nov 26</span> <a href="#">Elementum lorem</a>
              </li>
              <li>
                <span class="date">Nov 22</span> <a href="#">Lorem dolore nunc</a>
              </li>
              <li class="last">
                <span class="date">Nov 18</span> <a href="#">Accumsan et quis</a>
              </li>
            </ul>
          </div>
        </div>
        <div id="sidebar2">
          <h3>
            Tristique mauris duis
          </h3>
          <ul class="linkedList">
            <li class="first">
              <a href="#">Molestie dui vulputate</a>
            </li>
            <li>
              <a href="#">Mollis risus tellus nibh</a>
            </li>
            <li>
              <a href="#">Nascetur sit volutpat sapien</a>
            </li>
            <li>
              <a href="#">Mauris ante aliquet consequat</a>
            </li>
            <li>
              <a href="#">Ornare ipsum hendrerit</a>
            </li>
            <li class="last">
              <a href="#">Tellus est aliquam</a>
            </li>
          </ul>
          <h3>
            Magnis pharetra
          </h3><img class="top" src="<?php echo $this->basePath(); ?>/NikolaiBaldjiev/images/pic1.jpg" width="215" height="80" alt="" />
          <p>
            Pharetra rhoncus eu libero odio tempor feugiat. Porttitor sed fermentum vestibulum placerat. 
            Adipiscing proin ut iaculis id fringilla praesent quis. Lorem ipsum et dolor amet dolore
            consequat veroeros lorem sed amet et phasellus adipiscing sed etiam. Adipiscing proin sed 
            iaculis id fringilla praesent quis. Pharetra rhoncus eu libero odio tempor feugiat.
          </p>
        </div>
        <br class="clear" />
      </div>
      <div id="footer">
        <div id="footerContent">
          <h3>
            Accumsan mauris massa
          </h3>
          <p>
            Mattis semper erat enim condimentum posuere. Vitae sed adipiscing ante penatibus fusce accumsan fusce 
            curae. Arcu commodo interdum laoreet. Commodo diam tortor pharetra dignissim ipsum. Placerat ligula 
            dolor diam erat lorem. Curae facilisis fringilla dictum hendrerit volutpat. Imperdiet feugiat 
            phasellus lacinia integer ridiculus. Dignissim tristique vitae auctor nascetur curae luctus sed
            et consequat lorem.
          </p>
        </div>
        <div id="footerSidebar1">
          <h3>
            Sociis ultrices
          </h3>
          <p>
            Diam sed laoreet montes venenatis proin tellus cubilia.
          </p>
          <ul class="linkedList">
            <li class="first">
              <a href="#">Penatibus ligula dictum</a>
            </li>
            <li>
              <a href="#">Suscipit dolore consequat</a>
            </li>
            <li class="last">
              <a href="#">Parturient sed etiam</a>
            </li>
          </ul>
        </div>
        <div id="footerSidebar2">
          <h3>
            Fusce hendrerit
          </h3>
          <p>
            Diam sed laoreet montes venenatis proin tellus cubilia.
          </p>
          <ul class="linkedList">
            <li class="first">
              <a href="#">Elit feugiat pulvinar</a>
            </li>
            <li>
              <a href="#">Feugiat turpis sed justo</a>
            </li>
            <li class="last">
              <a href="#">Luctus facilisis mauris</a>
            </li>
          </ul>
        </div>
        <br class="clear" />
      </div>
    </div>
    <div id="copyright">
        &copy; Your Site Name | Design by <a href="http://www.freecsstemplates.org/">FCT</a>
    </div>
  </body>
</html>
