<?php echo $this->doctype() ?>

<!--

  Design by Free CSS Templates
  http://www.freecsstemplates.org
  Released for free under a Creative Commons Attribution License

  Name       : Faux Mocha
  Version    : 1.0
  Released   : 20130222

-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
		<?php echo $this->headMeta() ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink() ?>
		<?php echo $this->headScript() ?>
		<?php echo $this->headStyle() ?>
    </head>
    <body>
        <div id="outer">
            <div id="header">
                <div id="logo">
                    <h1>
                        <a href="#">Faux Mocha</a>
                    </h1>
                </div>
                <div id="nav">
                    <ul>
                        <li class="first">
                            <a href="#">Services We Offer</a>
                        </li>
                        <li>
                            <a href="#">Our Portfolio</a>
                        </li>
                        <li>
                            <a href="#">About Us</a>
                        </li>
                        <li class="last">
                            <a href="#">Contact Us</a>
                        </li>
                    </ul>
                    <br class="clear" />
                </div>
            </div>
            <div id="main">
                <div id="content">
                    <div id="box1">
                        <?php echo $this->content; ?>
                    </div>
                    <div id="box2">
                        <h3>
                            Volutpat amet dolor
                        </h3>
                        <p>
                            Tristique consectetur ridiculus congue cras commodo. Scelerisque lacus integer risus.
                        </p>
                        <ul class="linkedList">
                            <li class="first">
                                <a href="#">Donec volutpat lorem tellus</a>
                            </li>
                            <li>
                                <a href="#">Lobortis aenean congue sed etiam curabitur amet</a>
                            </li>
                            <li>
                                <a href="#">Cubilia praesent ante dignissim</a>
                            </li>
                            <li>
                                <a href="#">Consectetur placerat sapien eget aliquam dolore</a>
                            </li>
                            <li class="last">
                                <a href="#">Turpis id mollis ultricies</a>
                            </li>
                        </ul>
                    </div>
                    <div id="box3">
                        <h3>
                            Facilisis gravida
                        </h3><img class="top" src="<?php echo $this->basePath(); ?>/FmiStudent/images/pic2.jpg" width="225" height="140" alt="" />
                        <p>
                            Metus ultrices magna lorem vestibulum risus et lobortis. Nascetur nec tempor porttitor est urna. Cursus aliquet 
                            mus venenatis est viverra etiam suspendisse odio. Risus rutrum lorem at convallis diam. Sit amet lorem sed
                            consequat.
                        </p>
                    </div>
                    <br class="clear" />
                </div>
                <div id="sidebar1">
                    <h3>
                        Varius viverra
                    </h3>
                    <p>
                        Fringilla lobortis sit leo quis neque et ultricies placerat. Pretium ultricies et mauris 
                        accumsan cras id phasellus sed etiam pulvinar.
                    </p>
                    <ul class="linkedList">
                        <li class="first">
                            <a href="#">Nunc erat molestie nulla</a>
                        </li>
                        <li>
                            <a href="#">Sapien morbi augue</a>
                        </li>
                        <li>
                            <a href="#">Praesent mollis cras</a>
                        </li>
                        <li class="last">
                            <a href="#">Sollicitudin amet velit</a>
                        </li>
                    </ul>
                    <h3>
                        Nunc pharetra porta
                    </h3>
                    <ul class="linkedList">
                        <li class="first">
                            <a href="#">Malesuada sed dolore</a>
                        </li>
                        <li>
                            <a href="#">Cras nisl molestie</a>
                        </li>
                        <li>
                            <a href="#">Vivamus turpis lorem</a>
                        </li>
                        <li>
                            <a href="#">Volutpat porta purus</a>
                        </li>
                        <li class="last">
                            <a href="#">Molestie sagittis duis</a>
                        </li>
                    </ul>
                </div>
                <div id="sidebar2">
                    <h3>
                        Justo tempus
                    </h3>
                    <ul class="linkedList">
                        <li class="first">
                            <a href="#">Nascetur risus a tristique</a>
                        </li>
                        <li>
                            <a href="#">Duis risus amet egestas</a>
                        </li>
                        <li>
                            <a href="#">Turpis sem dolore magna amet consequat lorem</a>
                        </li>
            <li class="last">
              <a href="#">Cubilia praesent et dignissim</a>
            </li>
                    </ul>
                    <h3>
                        Felis imperdiet augue
                    </h3>
                    <p>
                        Eleifend nisl duis lorem orci consequat. Condimentum mus luctus mus et tincidunt. Metus ultrices magna 
                        amet vestibulum risus lobortis. Nascetur nec tempor porttitor est urna consequat lorem.
                    </p>
                    <ul class="linkedList">
                        <li class="first">
                            <a href="#">Dolor ligula sed fringilla</a>
                        </li>
                        <li>
                            <a href="#">Tellus parturient pharetra</a>
                        </li>
                        <li>
                            <a href="#">Lobortis consequat hendrerit suscipit dolore aliquam</a>
                        </li>
            <li class="last">
              <a href="#">Dolore aenean sed curabitur</a>
            </li>
          </ul>
                </div>
                <br class="clear" />
            </div>
        </div>
        <div id="copyright">
        &copy; Your Site Name | Design by <a href="http://www.freecsstemplates.org/">FCT</a>
        </div>
		<?php echo $this->inlineScript() ?>
    </body>
</html>
