<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Open Tools 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130803

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700|Archivo+Narrow:400,700" rel="stylesheet" type="text/css">
  <link href="<?php echo $this->basePath();?>/AlexanderAlexandrov/css/default.css" rel="stylesheet" type="text/css" media="all" />
<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<div id="header" class="container">
  <div id="logo">
    <h1><a href="#">Open Tools</a></h1>
  </div>
  <div id="menu">
    <ul>
      <li class="active"><a href="#" accesskey="1" title="">Homepage</a></li>
      <li><a href="#" accesskey="2" title="">My Designs</a></li>
      <li><a href="#" accesskey="3" title="">About Me</a></li>
      <li><a href="#" accesskey="4" title="">Contact</a></li>
    </ul>
  </div>
</div>
<div id="page" class="container">
  <div id="content">
    <div id="onecolumn">
      <p><img src="<?php echo $this->basePath();?>/AlexanderAlexandrov/images/pic01.png" width="580" height="300" alt="" /></p>
      
        <?php echo $this->content;?>
      
    </div>
    <div id="two-column">
      <div class="box-content">
        <h2 class="title title01">Nulla luctus eleifend</h2>
        <p>Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit. Nullam ante orci, pellentesque quis.</p>
      </div>
      <div class="box-content">
        <h2 class="title title02">Maecenas luctus lectus</h2>
        <p>Curabitur sit amet nulla. Nam in massa. Sed vel tellus. Curabitur sem urna, consequat vel, suscipit in, mattis placerat, nulla. Sed ac leo. Pellentesque imperdiet. In posuere  odio quisque semper augue mattis maecenas ligula.</p>
      </div>
    </div>
  </div>
  <div id="sidebar">
    <div id="sbox1">
      <h2>Fusce fringilla</h2>
      <ul class="list-style1">
        <li class="first">
          <p>Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus, cursus egestas at sem. </p>
          <p><a href="#" class="link-style">Read More</a></p>
        </li>
        <li>
          <p>Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus  at sem. </p>
          <p><a href="#" class="link-style">Read More</a></p>
        </li>
      </ul>
    </div>
    <div id="sbox2">
      <h2>Testimonials</h2>
      <p class="testimonial">Pellentesque adipiscing purus ac magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames.</p>
      <div class="author"><img src="<?php echo $this->basePath();?>/AlexanderAlexandrov/images/pic03.jpg" width="80" height="80" alt="" /><span class="name">Juan Dela Cruz</span><span class="position">Company CEO</span><span>MyCompany, LLC</span></div>
    </div>
    <div id="sbox3">
      <h2>Vestibulum luctus</h2>
      <ul class="style3">
        <li class="first"><a href="#">Consectetuer adipiscing elit</a></li>
        <li><a href="#">Metus aliquam pellentesque</a></li>
        <li><a href="#">Suspendisse iaculis mauris</a></li>
        <li><a href="#">Urnanet non molestie semper</a></li>
        <li><a href="#">Proin gravida orci porttitor</a></li>
      </ul>
    </div>
  </div>
</div>
<div id="footer" class="container">
  <div id="fbox1">
    <h2>Aenean elementum</h2>
    <ul class="style1">
      <li class="first"><a href="#">Consectetuer adipiscing elit</a></li>
      <li><a href="#">Metus aliquam pellentesque</a></li>
      <li><a href="#">Suspendisse iaculis mauris</a></li>
      <li><a href="#">Urnanet non molestie semper</a></li>
      <li><a href="#">Proin gravida orci porttitor</a></li>
    </ul>
  </div>
  <div id="fbox2">
    <h2>Vestibulum luctus</h2>
    <ul class="style1">
      <li class="first"><a href="#">Consectetuer adipiscing elit</a></li>
      <li><a href="#">Metus aliquam pellentesque</a></li>
      <li><a href="#">Suspendisse iaculis mauris</a></li>
      <li><a href="#">Urnanet non molestie semper</a></li>
      <li><a href="#">Proin gravida orci porttitor</a></li>
    </ul>
  </div>
  <div id="fbox3">
    <h2>Etiam malesuada</h2>
    <p>In posuere eleifend odio. Quisque semper augue mattis wisi. Maecenas ligula. Pellentesque viverra vulputate enim. Donec leo. Vivamus fermentum nibh in augue.</p>
    <ul class="style2">
      <li><a href="#"><img src="<?php echo $this->basePath();?>/AlexanderAlexandrov/images/social03.png" width="32" height="32" alt="" /></a></li>
      <li><a href="#"><img src="<?php echo $this->basePath();?>/AlexanderAlexandrov/images/social01.png" width="32" height="32" alt="" /></a></li>
      <li><a href="#"><img src="<?php echo $this->basePath();?>/AlexanderAlexandrov/images/social04.png" width="32" height="32" alt="" /></a></li>
      <li><a href="#"><img src="<?php echo $this->basePath();?>/AlexanderAlexandrov/images/social02.png" width="32" height="32" alt="" /></a></li>
    </ul>
  </div>
</div>
<div id="copyright" class="container">
  <p>Copyright (c) 2013 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org">FCT</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
</div>
</body>
</html>
