<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="" name="keywords" />
  <meta content="" name="description" />
  <meta content="text/html; charset=utf-8" http-equiv="content-type" />
  <title>Eponymous by FCT</title>
  <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
  <link head="" href="<?php echo $this->basePath(); ?>/ZhelyanGuglev/eponymous/style.css" rel="stylesheet" type="text/css" />
 </head>
 <body>
  <div id="bg">
   <div id="outer">
    <div id="header">
     <div id="logo">
      <h1>
       <a href="#">Eponymous</a></h1>
     </div>
     <div id="nav">
      <ul>
       <li class="first active">
        <a href="#">Home</a></li>
       <li>
        <a href="#">Services</a></li>
       <li>
        <a href="#">Blog</a></li>
       <li>
        <a href="#">Portfolio</a></li>
       <li>
        <a href="#">About</a></li>
       <li class="last">
        <a href="#">Contact</a></li>
      </ul>
     </div>
    </div>
    <div id="banner">
     <img alt="" height="200" src="<?php echo $this->basePath(); ?>/ZhelyanGuglev/eponymous/images/pic1.jpg" width="1120" /></div>
    <div id="main">
     <div id="sidebar">
      <h3>
       Nascetur etiam et consequat amet</h3>
      <p>
       Suspendisse pretium leo convallis. Viverra augue euismod sodales etiam volutpat. Vulputate amet sapien quis placerat et vulputate. Lorem ipsum dolor sit amet.</p>
      <ul class="linkedList">
       <li class="first">
        <a href="#">Nulla diam vivamus</a></li>
       <li>
        <a href="#">Pretium mollis cubilia</a></li>
       <li>
        <a href="#">Auctor est fermentum</a></li>
       <li>
        <a href="#">Praesent est ullamcorper</a></li>
       <li class="last">
        <a href="#">Volutpat et blandit</a></li>
      </ul>
     </div>
     <div id="content">
      <div id="box1">
       <h2>
        Welcome to Eponymous</h2>
        <h2><?php echo $this->content; ?></h2>
       <img alt="" class="left" height="140" src="<?php echo $this->basePath(); ?>/ZhelyanGuglev/eponymous/images/pic2.jpg" width="170" />
       <p>
        This is <strong>Eponymous</strong>, a two column CSS template by <a href="http://www.freecsstemplates.org/">FCT</a> with photos from <a href="http://www.pdphoto.org/">PDPhoto</a>. It&#39;s released (for free) under the <a href="http://www.freecsstemplates.org/license/">Creative Commons Attribution 3.0 license</a>, so feel free to use it for any personal or commercial work, just keep our footer credit links intact. Hit up our <a href="http://www.freecsstemplates.org/">website</a> for more awesomely cool free templates, and follow us on <a href="http://twitter.com/freecsstemplate">Twitter</a> (<a href="http://twitter.com/freecsstemplate">@freecsstemplate</a>) for updates, announcements, and other interesting ramblings.</p>
      </div>
      <div id="box2">
       <h3>
        Fringilla nisi parturient nullam</h3>
       <p>
        Elementum sodales est varius magna leo sociis erat. Nascetur pretium non ultricies gravida. Condimentum at nascetur tempus. Porttitor viverra ipsum accumsan neque aliquet. Ultrices vestibulum tempor quisque eget sem eget. Ornare malesuada tempus dolor dolor magna consectetur. Nisl dui non curabitur laoreet tortor.</p>
       <ul class="linkedList">
        <li class="first">
         <a href="#">Neque ac iaculis nisl nibh ipsum egestas mattis</a></li>
        <li>
         <a href="#">Commodo enim nisl turpis magnis enim morbi</a></li>
        <li>
         <a href="#">Convallis purus curae non sollicitudin posuere dolor ante</a></li>
        <li>
         <a href="#">Gravida magna dignissim imperdiet leo quisque</a></li>
        <li class="last">
         <a href="#">Sapien hendrerit venenatis dis nec lobortis pharetra</a></li>
       </ul>
      </div>
     </div>
    </div>
    <div id="footer">
     <div id="footerSidebar">
      <h3>
       Odio adipiscing</h3>
      <ul class="linkedList">
       <li class="first">
        <a href="#">Curabitur mus posuere</a></li>
       <li>
        <a href="#">Penatibus et accumsan</a></li>
       <li class="last">
        <a href="#">Convallis sed ornare</a></li>
      </ul>
     </div>
     <div id="footerContent">
      <h3>
       Proin dolor nullam</h3>
      <p>
       Magna euismod risus interdum vulputate viverra. Urna ultrices vitae ornare volutpat. Pellentesque penatibus semper aliquam mollis. Urna lobortis elit eget a dignissim rutrum. Integer ipsum ligula sociis tellus quam enim. Nibh nec phasellus mattis montes faucibus malesuada. Venenatis cubilia odio volutpat phasellus facilisis ultricies convallis. Convallis purus urna suspendisse consectetur feugiat. Varius dignissim aliquet montes libero. Consectetur a lobortis nulla montes quisque blandit. Primis eget vestibulum pretium turpis.</p>
     </div>
    </div>
   </div>
   <div id="copyright">
    &copy; Your Site Name | Design by <a href="http://www.freecsstemplates.org/">FCT</a></div>
  </div>
 </body>
</html>
